AWS_STACK_NAME = hello-world
AWS_PROFILE = hello-world-profile
AWS_REGION=eu-west-2
STAGE_NAME?=dev

.PHONY:clean
clean:
	cd backend && $(MAKE) clean AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) clean

.PHONY:install
install:
	cp scripts/githooks/* .git/hooks
	cd backend && $(MAKE) install  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION)  STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) install STAGE_NAME=$(STAGE_NAME)

.PHONY:local-env
local-env:
	cd backend && $(MAKE) local-env  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION)  STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) local-env STAGE_NAME=$(STAGE_NAME)

.PHONY:build
build:	
	cd backend && $(MAKE) build STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) build STAGE_NAME=$(STAGE_NAME)

.PHONY:start
start:
	$(MAKE) start-api start-app -j 2 STAGE_NAME=$(STAGE_NAME)

.PHONY:start-api
start-api:
	(cd backend && $(MAKE) start AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION)  STAGE_NAME=$(STAGE_NAME)) 

.PHONY:start-app
start-app:
	(cd app && $(MAKE) start  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION)  STAGE_NAME=$(STAGE_NAME))

.PHONY:test
test: 
	cd backend && $(MAKE) test AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME) AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) test AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME) AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)

.PHONY:package
package: 
	cd backend && $(MAKE) package  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME) AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
#	cd app && $(MAKE) package  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)

.PHONY:outputs
outputs: 
	cd backend && $(MAKE) outputs  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) outputs  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)

.PHONY:deploy
deploy: 
	cd backend && $(MAKE) deploy  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) deploy  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION)  STAGE_NAME=$(STAGE_NAME)

.PHONY:infrastructure
infrastructure: 
	cd backend && $(MAKE) infrastructure  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
	cd app && $(MAKE) infrastructure  AWS_PROFILE=$(AWS_PROFILE) AWS_STACK_NAME=$(AWS_STACK_NAME)  AWS_REGION=$(AWS_REGION) STAGE_NAME=$(STAGE_NAME)
