AWSTemplateFormatVersion: '2010-09-09'
Description: "API Stack CFN template"
Resources:
  HelloWorldApiServerlessStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./serverless-stack.yaml
  HelloWorldApiStorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./storage-stack.yaml 

Outputs:
  StorageStackRef:
    Value: !Ref HelloWorldApiStorageStack

  ServerlessStackRef:
    Value: !Ref HelloWorldApiServerlessStack

  ServerlessStackHelloWorldApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !GetAtt HelloWorldApiServerlessStack.Outputs.HelloWorldApiEndpoint
    
  ServerlessStackHelloWorldFunctionArn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldApiServerlessStack.Outputs.HelloWorldFunction
    
  ServerlessStackHelloWorldApiRole:
    Description: "IAM Role created for Hello World Api"
    Value: !GetAtt HelloWorldApiServerlessStack.Outputs.HelloWorldApiRole