AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello World Api
Globals:
  Function:
    Timeout: 30
Parameters:
  StageName: 
    Type: String
    Description: "The stage name to deploy to."
  RoleArn:
    Type: String
    Description: "The arn of the Role to use for the Api"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../api/swagger.yaml
  HelloWorldJsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../api/nodejs/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Role: !Ref RoleArn
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          StageName: !Ref StageName
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello-world-js
            Method: POST

  CustomResourceSeedDynamoDbFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../api/custom-resources/seed-dynamodb/      
      Handler: app.handler
      Runtime: nodejs8.10
      Role: !Ref RoleArn
      Timeout: 60
      
  CustomResourceEmptyBucketFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../api/custom-resources/empty-bucket/      
      Handler: index.handler
      Runtime: nodejs8.10
      Role: !Ref RoleArn
      Timeout: 60

Outputs:
  ApiEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  
  HelloWorldJsFunctionArn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldJsFunction.Arn

  CustomResourceSeedDynamoDbFunctionArn:
    Description: "ARN of the function that seeds dynamodb resources"
    Value: !GetAtt CustomResourceSeedDynamoDbFunction.Arn
    
  CustomResourceEmptyBucketFunctionArn:
    Description: "ARN of the function that clears a S3 bucket"
    Value: !GetAtt CustomResourceEmptyBucketFunction.Arn
