AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello World Api
Globals:
  Function:
    Timeout: 30

Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: api-role
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - PolicyName: api-role-policy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../api/swagger.yaml
            
  HelloWorldJsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../api/nodejs/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Role: !GetAtt ApiRole.Arn
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello-world-js
            Method: POST
  
  HelloWorldGoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../api/go/build/main.zip
      Handler: main
      Runtime: go1.x
      Role: !GetAtt ApiRole.Arn
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello-world-go
            Method: POST

Outputs:
  ApiEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  HelloWorldJsFunctionArn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldJsFunction.Arn

  ApiRoleArn:
    Description: "IAM Role created for the Api Gateway"
    Value: !GetAtt ApiRole.Arn

  HelloWorldGoFunctionArn:
    Description: "Hello World Go Lambda Function ARN"
    Value: !GetAtt HelloWorldGoFunction.Arn