AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World Hosting Stack 
Parameters:
  StageName: 
    Type: String
    Description: "The stage name to deploy to."
  CustomResourceEmptyBucketFunctionArn: 
    Type: String
    Description: "The ARN of the lambda for the lambda backed clear bucket custom resource "
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "hello-world-hosting-${StageName}"
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            MaxAge: '30'
      WebsiteConfiguration:
        IndexDocument: index.html

  CustomResourceEmptyBucket:
    DependsOn: WebsiteBucket
    Type: Custom::CustomResourceEmptyBucket
    Properties:
      ServiceToken: 
        Ref: CustomResourceEmptyBucketFunctionArn
      Region: !Ref "AWS::Region"
      BucketName: !Ref WebsiteBucket
Outputs:
  WebsiteBucketName:
    Value: !Ref WebsiteBucket
    Description: The bucket name of our website bucket
  WebsiteURL:
    Value: !GetAtt [WebsiteBucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [WebsiteBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content