AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World Hosting Stack
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
Outputs:
  WebsiteBucketName:
    Value: !Ref WebsiteBucket
    Description: The bucket name of our website bucket
  WebsiteURL:
    Value: !GetAtt [WebsiteBucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [WebsiteBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content