AWSTemplateFormatVersion: '2010-09-09'
Description: "API Stack CFN template"
Parameters:
  StageName: 
    Type: String
    Description: "The stage name to deploy to."
Resources:
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./auth-stack.yaml
      Parameters:
        StageName: !Ref StageName
  HostingStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./hosting-stack.yaml
      Parameters:
        StageName: !Ref StageName
        CustomResourceEmptyBucketFunctionArn: !GetAtt ApiStack.Outputs.CustomResourceEmptyBucketFunctionArn
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api-stack.yaml
      Parameters:
        StageName: !Ref StageName
        RoleArn: !GetAtt AuthStack.Outputs.ApiRoleArn
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./storage-stack.yaml 
      Parameters:
        StageName: !Ref StageName 
        CustomResourceSeedDynamoDbFunctionArn: !GetAtt ApiStack.Outputs.CustomResourceSeedDynamoDbFunctionArn

Outputs:
  StorageStackRef:
    Value: !Ref StorageStack

  ApiStackRef:
    Value: !Ref ApiStack

  ApiEndpointUrl:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !GetAtt ApiStack.Outputs.ApiEndpointUrl
    
  ClientWebsiteUrl:
    Description: "The URL used to access the frontend website"
    Value: !GetAtt HostingStack.Outputs.S3BucketSecureURL

  ClientWebsiteBucketName:
    Description: "The S3 Bucket name used to host the client website"
    Value: !GetAtt HostingStack.Outputs.WebsiteBucketName
