AWSTemplateFormatVersion: '2010-09-09'
Description: API Stack CFN template
Outputs:
  ApiEndpointUrl:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::GetAtt:
      - ApiStack
      - Outputs.ApiEndpointUrl
  ApiRoleArn:
    Description: IAM Role created for Hello World Api
    Value:
      Fn::GetAtt:
      - ApiStack
      - Outputs.ApiRoleArn
  ApiStackRef:
    Value:
      Ref: ApiStack
  ClientWebsiteBucketName:
    Description: The S3 Bucket name used to host the client website
    Value:
      Fn::GetAtt:
      - HostingStack
      - Outputs.WebsiteBucketName
  ClientWebsiteUrl:
    Description: The URL used to access the frontend website
    Value:
      Fn::GetAtt:
      - HostingStack
      - Outputs.S3BucketSecureURL
  StorageStackRef:
    Value:
      Ref: StorageStack
Parameters:
  StageName:
    Description: The stage name to deploy to.
    Type: String
Resources:
  ApiStack:
    Properties:
      Parameters:
        StageName:
          Ref: StageName
      TemplateURL: https://s3.amazonaws.com/hello-world-abbottdev/73779a9490f3533d0844631272675912.template
    Type: AWS::CloudFormation::Stack
  HostingStack:
    Properties:
      Parameters:
        StageName:
          Ref: StageName
      TemplateURL: https://s3.amazonaws.com/hello-world-abbottdev/fcabb02f04acda56d4bc195cad9a5abf.template
    Type: AWS::CloudFormation::Stack
  StorageStack:
    Properties:
      Parameters:
        SeederLambdaFunctionArn:
          Fn::GetAtt:
          - ApiStack
          - Outputs.SeederJsFunctionArn
        StageName:
          Ref: StageName
      TemplateURL: https://s3.amazonaws.com/hello-world-abbottdev/c5a0e835455b4bbefe43c64b9ef1a85f.template
    Type: AWS::CloudFormation::Stack
