AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A dynamo db that stores random nouns which can be queried by an AWS lambda
Parameters:
  StageName: 
    Type: String
    Description: "The stage name to deploy to." 
  CustomResourceSeedDynamoDbFunctionArn:
    Type: String
    Description: "The ARN of the Lambda function used to seed resources"

Resources:
  NounDbStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ../storage/noun-db/noun-db-stack.yaml 
      Parameters:
        StageName: !Ref StageName
        CustomResourceSeedDynamoDbFunctionArn: !Ref CustomResourceSeedDynamoDbFunctionArn
