AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A dynamo db that stores random nouns which can be queried by an AWS lambda
Parameters:
  StageName: 
    Type: String
    Description: "The stage name to deploy to."
  CustomResourceSeedDynamoDbFunctionArn:
    Type: String
    Description: Arn of the Lambda function used to initialise this resource

Resources:
  NounDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "NounDynamoDbTable-${StageName}"
      AttributeDefinitions:
      - AttributeName: NounId
        AttributeType: S
      KeySchema:
      - AttributeName: NounId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SeedNounDynamoDbTable:
    DependsOn: NounDynamoDbTable
    Type: Custom::DynamoDbSeederResource
    Properties:
      ServiceToken: 
        Ref: CustomResourceSeedDynamoDbFunctionArn
      Region: !Ref "AWS::Region"
      TableName: !Ref NounDynamoDbTable
      RequestItems:
        - PutRequest:
            Item:
              NounId:
                S: "1"
              NounName:
                S: "Hello"
        - PutRequest:
            Item:
              NounId:
                S: "2"
              NounName:
                S: "Bonjour"
        - PutRequest:
            Item:
              NounId:
                S: "3"
              NounName:
                S: "Hallo"
        - PutRequest:
            Item:
              NounId:
                S: "4"
              NounName:
                S: "Olá"
        - PutRequest:
            Item:
              NounId:
                S: "5"
              NounName:
                S: "Hej"