AWSTemplateFormatVersion: '2010-09-09'
Description: API Stack CFN template
Outputs:
  OutputFromNestedStack:
    Value:
      Fn::GetAtt:
      - HelloWorldApiServerlessStack
      - Outputs.HelloWorldApiEndpoint
  StackRef:
    Value:
      Ref: HelloWorldApiServerlessStack
Resources:
  HelloWorldApiServerlessStack:
    Properties:
      TemplateURL: https://s3.amazonaws.com/hello-world-abbottdev/84d9958f83dd686229ed6c4d83a6fcfe.template
    Type: AWS::CloudFormation::Stack
  HelloWorldApiStorageStack:
    Properties:
      TemplateURL: https://s3.amazonaws.com/hello-world-abbottdev/8417281c897c2fa51932f0302da33a1a.template
    Type: AWS::CloudFormation::Stack
